resolver: lts-10.0

packages:
 - '.'

 - location:
     git: https://github.com/f-o-a-m/hs-web3
     commit: 17d204a9668eac66936a695459088bdaafd28f18
   extra-dep: true

 - location:
     git: https://github.com/f-o-a-m/selda
     commit: 64993ae4f4249df1222691fcb6341367fb8c68d4
     subdirs:
       - selda 
       - selda-postgresql
   extra-dep: true

# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#   extra-dep: true
#  subdirs:
#  - auto-update
#  - wai

extra-deps:
 - sized-0.2.1.1
 - equational-reasoning-0.5.0.0
 - monomorphic-0.0.3.3
 - type-natural-0.7.1.4
 - presburger-1.3.1
 - ghc-typelits-presburger-0.1.1.1
 - secp256k1-0.5.2

